name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django djangorestframework

      - name: Create Django Project
        run: |
          python -m django startproject mysite

      - name: Copy blog to mysite
        run: |
          cd mysite
          git clone https://github.com/youzarsiph/blog

      - name: Add blog to INSTALLED_APPS
        run: |
          cd mysite
          echo "INSTALLED_APPS += ['blog', 'blog.articles', 'blog.comments', 'blog.followers', 'blog.reactions', 'blog.tags', 'blog.users', 'rest_framework']" >> mysite/settings.py
          echo "AUTH_USER_MODEL = 'users.User'" >> mysite/settings.py

      - name: Add blog to mysite URLConf
        run: |
          cd mysite
          echo "urlpatterns += [path("", include("blog.urls"))]" >> mysite/urls.py

      - name: Run Check
        run: |
          cd mysite
          python manage.py check

      - name: Run Migrations
        run: |
          cd mysite
          python manage.py migrate

      - name: Run Tests
        run: |
          cd mysite
          python manage.py test
