name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django djangorestframework

      - name: Create Django Project
        run: |
          python -m django startproject project

      - name: Copy blog to project
        run: |
          cd project
          git clone https://github.com/youzarsiph/blog

      - name: Add blog to INSTALLED_APPS
        run: |
          echo "INSTALLED_APPS += ['blog', 'blog.articles', 'blog.comments', 'blog.followers', 'blog.reactions', 'blog.tags', 'blog.users', 'rest_framework']\nAUTH_USER_MODEL = 'users.User'" >> project/settings.py

      - name: Add blog to project URLConf
        run: |
          echo "urlpatterns += [path("", include("blog.urls"))]" >> project/urls.py

      - name: Run Check
        run: |
          python manage.py check

      - name: Run Migrations
        run: |
          python manage.py migrate

      - name: Run Tests
        run: |
          python manage.py test
