name: Ruff

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff django

      - name: Analyzing the code with Ruff
        run: |
          ruff check $(git ls-files '*.py')
